#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Console\Application;
use minapp\system\buildDatabase;

$application = new Application();
$application->add(new buildDatabase());
$application->run();